### ISSUE TITLE
Null pointer exception on windows

### ISSUE THREAD

**Issue by enpboss** [nyholku/purejavahidapi#7]
I am getting nullpointer exception on windows while opening the device. device is null. 
but device is listed.

**Comment by psit** [comment]
Same here. Just checked out revision 8a474bf0dd0ac7723ebdca5922caefaecf0c56a8.
System is WinXP in Virtual Box on Linux Host.
Example2 worked great on linux host, but fails on WinXP guest with `PureJavaHidApi.openDevice()` returning null. Info including path was given:
`VID = 0x0B0E PID = 0x0345 Manufacturer = Jabra Product = null Path = \\?\hid#vid_0b0e&pid_0345&mi_03&col01#7&5cd08ce&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}`

**Comment by psit** [comment]
Additional Information:
Example also failed on WinXP with Java 8u40 and Win7 with Java 8u40.
Further, the device creates 3 USB devices in Windows (1 in Linux). All of the 3 result in openDevice() returning null.
The problem comes down to `WindowsBackend.openDevice(path, false)` returning `INVALID_HANDLE_VALUE`.

Forcing the share_mode in WindowsBackend to `FILE_SHARE_READ|FILE_SHARE_WRITE` lets the handle be valid. But the example code uses 100% CPU.

**Comment by nyholku** [comment]
@psit @enpboss

Have you checked that you can open the device with any other program?

If you look at the code in the Windows backend you see that it is simply a thin wrapper for call to the CreateFile and thus hard to believe the issues is with PJC. If it fails the port/file simply cannot be opened. Most likely because someone else is using it. @psit If "Forcing the share_mode in WindowsBackend to FILE_SHARE_READ|FILE_SHARE_WRITE" seems to help, this is a further indication that someone else is using it and sharing a serial port is not supported so hacking like that is sure to cause problems as evidenced by 100% CPU usage.

**Comment by psit** [comment]
I don't think, that the device is blocked. I can log all button events with USB HID Logger (https://www.aggsoft.com/usb-hid-logger/ - there is a trial version).

I tried a little more. Now I set the desired_access to `GENERIC_READ` and this works as well (instead of `GENERIC_WRITE | GENERIC_READ`). I leave the share_mode as it is.
Still, as long as the device is open, CPU is at 100 %. I changed the listener to close the device after the first event. Now if I press a button (and the event is recognized, which is not necessarily the case), the device is closed and the example program terminates.

Looking into `runReadOnBackground` shows, that the devices thread does not wait and thus the while loop uses 100 % CPU.

**Comment by nyholku** [comment]
Ok, sorry, I answered in a hurry and got my wires crossed, this is a rather common situation in my other PureJavaComm project and I got confused what I was responding to. So can you share your code sample so I can see better what you are talking about.

**Comment by psit** [comment]
Well, I don't know what has changed, but now I don't get any NullPointer Exceptions any longer, when opening the device. I can now even open and close and reopen it. (Possibly the devices service that got installed interferred in the background. I recently uninstalled it.)

Still, the bug remains, that `purejavahidapi.windows.HidDevice.runReadOnBackground()` runs at 100 % CPU, as there is no waiting within the while loop.
I guess some method should block until data is available, but unfortunately, the calls don't block.
`ReadFile` is constantly returning false, `m_InputReportBytesRead[0]` is always 0 (when I add debugging output, which creates a LOT of output because of the loop running without wait).

When I disable debugging output, I occasionally capture some data (about 1/5 of all button presses are detected). Of course, if the events are detected, ReadFile is true and bytes read are non-zero.

**Comment by nyholku** [comment]
I will try to have a look at this issue over the Eastern holidays.

br Kusti


> psit <mailto:notifications@github.com>
> 1 April 2015 17:53
> Well, I don't know what has changed, but now I don't get any 
> NullPointer Exceptions any longer, when opening the device. I can now 
> even open and close and reopen it. (Possibly the devices service that 
> got installed interferred in the background. I recently uninstalled it.)
>
> Still, the bug remains, that 
> `purejavahidapi.windows.HidDevice.runReadOnBackground()` runs at 100 % 
> CPU, as there is no waiting within the while loop.
> I guess some method should block until data is available, but 
> unfortunately, the calls don't block.
> `ReadFile` is constantly returning false, `m_InputReportBytesRead[0]` 
> is always 0 (when I add debugging output, which creates a LOT of 
> output because of the loop running without wait).
>
> When I disable debugging output, I occasionally capture some data 
> (about 1/5 of all button presses are detected). Of course, if the 
> events are detected, ReadFile is true and bytes read are non-zero.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nyholku/purejavahidapi/issues/7#issuecomment-88512793
> Poovizhirajan.N <mailto:notifications@github.com>
> 13 March 2015 09:27
> I am getting nullpointer exception on windows while opening the 
> device. device is null.
> device is listed in the list.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nyholku/purejavahidapi/issues/7

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by nyholku** [comment]
I pushed some changes to the Windows backend that might help, or not.

**Comment by psit** [comment]
Whatever these changes where in detail, it works (on the above mentioned WinXP virtual machine - Need to check on Win7 physical installation)!
Great job! Thank you!
Maybe the OP can check if his issue is resolved too.

**Comment by rinick** [comment]
I still have this issue,
I'm running windows 10 64bit  java 1.8.0_25
I can find the device but can't open it.

**Comment by nyholku** [comment]
Exactly *issue*?

**Comment by rinick** [comment]
```
	public purejavahidapi.HidDevice openDevice(String path, Frontend frontend) {
		m_Frontend = frontend;
		HANDLE handle = open_device(path, false);

		// Check validity of write_handle.
		if (handle == INVALID_HANDLE_VALUE) {
```
here `handle == INVALID_HANDLE_VALUE` is always true

**Comment by nyholku** [comment]
Well, if you look at open_device in the Windows backend here:

https://github.com/nyholku/purejavahidapi/blob/master/src/purejavahidapi/windows/WindowsBackend.java

you see that it is basically a just a call to Windows API CreateFile ... so if that fails the issues is likely to be with Windows, the device, or some other application, but not with PureJavaHidApi. Most likely some other application or service has the device in use. What device is this?

**Comment by rinick** [comment]
I tried my mouse, keyboard, and a PS4 controller (connected to PC via bluetooth), all have same issue.  but this C# application is able to connect the PS4 controller. https://github.com/Jays2Kings/DS4Windows.

**Comment by nyholku** [comment]
> On 10 Oct 2015, at 19:42, Rick Zhou <notifications@github.com> wrote:
> 
> I tried my mouse, keyboard, and a PS4 controller (connected to PC via bluetooth), all have same issue. but this C# application is able to connect the PS4 controller. https://github.com/Jays2Kings/DS4Windows.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Very hard for me to debug this since I don't have Windows 10 or PS4 controller. I suggest you study the DS4Windows program to see how it opens the devices and how that differs from what PureJavaHidApi works, should be straight forward.

br Kusti

**Comment by rinick** [comment]
found the issue, shared mode must be both `FILE_SHARE_READ | FILE_SHARE_WRITE` otherwise  `CreateFileA` will fail with an invalid handler

**Comment by nyholku** [comment]
This has been fixed sometime ago, so I'm closing this. Feel free to open if the problem persists.
